$(document).ready(function(){
    $("#elvis").click(function(){
        $("#elvis-showing").toggle();
        $("#elvis-hidden").toggle();
    })
    $("#brian").click(function(){
        $("#brian-showing").toggle();
        $("#brian-hidden").toggle();
    })
    $("#kelvin").click(function(){
        $("#kelvin-showing").toggle();
        $("#kelvin-hidden").toggle();
    })
    $("#me").click(function(){
        $("#me-showing").toggle();
        $("#me-hidden").toggle();
    })
})